### ISSUE TITLE
App crashes if phone rotates while drill or category edit fragment is open

### ISSUE THREAD

**Issue by araneforseti** [araneforseti/drill_tracker#1]
`com.forseti.drilltracker E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.forseti.drilltracker, PID: 4216
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.forseti.drilltracker/com.forseti.drilltracker.DrillTrackerMain}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.forseti.drilltracker.adapter.ExpandableDrillListAdapter.getCategories()' on a null object reference
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:151)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.forseti.drilltracker.adapter.ExpandableDrillListAdapter.getCategories()' on a null object reference
                                                                            at com.forseti.drilltracker.views.CreateDrillFragment.onCreateDialog(CreateDrillFragment.java:54)
                                                                            at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
                                                                            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
                                                                            at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
                                                                            at android.app.Activity.performCreateCommon(Activity.java:5985)
                                                                            at android.app.Activity.performCreate(Activity.java:5992)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) `

**Comment by araneforseti** [comment]
Fixed with 94621c2
